version: "3.2"

services:
  messaging:
    build: 'messaging'
    image: thefirstspine_messaging_image
    container_name: thefirstspine_messaging_container
    networks:
      default:
    volumes:
      - /var/log:/var/log
    ports:
      - "${PORT}:${PORT}"
    tty: true
    env_file:
      - .env

networks:
  default:
    driver: bridge
